### ISSUE TITLE
Missing function doShift()

### ISSUE THREAD

**Issue by MartinK84** [fmrilab/NonCrtGRAPPA#2]
When running the Cartesian demo (_do_Cartesian(phmA)_) from _demo_GRAPPA.m_ it appears that the function **doShift()** is missing. It's used by the file _patch2row.m_ in line 31.

**Comment by tianrluo** [comment]
@MartinK84 Thanks for pointing that out!
Just updated the repo, would you check it out and let me know if it's fixed?
(It's not very easy to switch to a fresh Matlab environment for testing...)

**Comment by MartinK84** [comment]
@tianrluo Thanks for the quick response, the Demo works now!
